BACK_TO_RECIPES_BUTTON_TEXT = "Back To Recipes"
CREATE_NEW_RECIPE_BUTTON_TEXT = "Create New Recipe"
CREATE_NEW_RECIPE_FORM_TEXT = "Create New Recipe"
CREATE_RECIPE_BUTTON_TEXT = "Create Recipe"
DELETE_RECIPE_BUTTON_TEXT = "Delete Recipe"
EDIT_RECIPE_BUTTON_TEXT = "Edit Recipe"
EDIT_RECIPE_FORM_TITLE_TEXT = "Edit This Recipe"
HOME_BUTTON_TEXT = "Home"
HOME_HEADER_TEXT = "Food Recipes"
NO_PHOTO_PLACEHOLDER_ADDRESS = "Sammy_Meal.jpg"
    # or you could use "https://via.placeholder.com/150?text=NO+PHOTO"
RECIPES_INDEX_HEADER_TEXT = "Recipes for every occasion!"
RECIPE_FORM_NAME_FIELD = "Recipe Name"
RECIPE_FORM_INGREDIENTS_FIELD = "Ingredients"
RECIPE_FORM_INSTRUCTIONS_FIELD = "Instructions"
UPDATE_RECIPE_BUTTON_TEXT = "Update Recipe"
VIEW_RECIPE_BUTTON_TEXT = "View Recipe"
VIEW_RECIPES_BUTTON_TEXT = "View Recipes"


